"""add job processing status table

Revision ID: 795c10e7c423
Revises: 58734e5510eb
Create Date: 2025-10-06 20:22:12.663907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '795c10e7c423'
down_revision: Union[str, Sequence[str], None] = '58734e5510eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_processing_statuses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('tag', sa.Enum('JOB_PARSED_AT', 'EDUCATIONS_SELECTED_AT', 'WORK_EXPERIENCES_SELECTED_AT', 'PROJECTS_SELECTED_AT', 'SKILLS_SELECTED_AT', name='processing_status_tag'), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_job_processing_statuses_job_id_jobs')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_job_processing_statuses_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_processing_statuses')),
    sa.UniqueConstraint('user_id', 'job_id', 'tag', name='uq_job_processing_statuses_user_job_tag')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_processing_statuses')
    # ### end Alembic commands ###
