"""Make proficiency_level optional in UserSkill

Revision ID: 9b9c400107f9
Revises: a649032e370d
Create Date: 2025-08-14 14:02:43.457800

"""
from typing import Sequence, Union

from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9b9c400107f9'
down_revision: Union[str, Sequence[str], None] = 'a649032e370d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_skills', 'proficiency_level',
               existing_type=postgresql.ENUM('BEGINNER', 'ELEMENTARY', 'INTERMEDIATE', 'ADVANCED', 'EXPERT', name='proficiencylevel'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_skills', 'proficiency_level',
               existing_type=postgresql.ENUM('BEGINNER', 'ELEMENTARY', 'INTERMEDIATE', 'ADVANCED', 'EXPERT', name='proficiencylevel'),
               nullable=False)
    # ### end Alembic commands ###
