"""Change embedding column from JSON to vector

Revision ID: a649032e370d
Revises: f24ddb1606a6
Create Date: 2025-08-10 16:39:17.583279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = 'a649032e370d'
down_revision: Union[str, Sequence[str], None] = 'f24ddb1606a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_responsibility_skill_mapping', 'responsibility_skill_mappings', ['user_id', 'skill_id', 'responsibility_id'])
    # Use raw SQL for the type conversion since the table is empty
    op.execute("ALTER TABLE skills ALTER COLUMN embedding TYPE vector(1536) USING embedding::text::vector(1536)")
    op.create_unique_constraint('uq_task_skill_mapping', 'task_skill_mappings', ['user_id', 'skill_id', 'task_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_task_skill_mapping', 'task_skill_mappings', type_='unique')
    op.alter_column('skills', 'embedding',
               existing_type=Vector(1536),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False)
    op.drop_constraint('uq_responsibility_skill_mapping', 'responsibility_skill_mappings', type_='unique')
    # ### end Alembic commands ###
