model_list:
  # OpenAI Models
  - model_name: gpt-4.1
    litellm_params:
      model: openai/gpt-4.1
      api_key: os.environ/OPENAI_API_KEY # Set in environment variable

  - model_name: gpt-4.1-mini
    litellm_params:
      model: openai/gpt-4.1-mini
      api_key: os.environ/OPENAI_API_KEY

  - model_name: gpt-4o
    litellm_params:
      model: openai/gpt-4o
      api_key: os.environ/OPENAI_API_KEY

  - model_name: gpt-3.5-turbo
    litellm_params:
      model: openai/gpt-3.5-turbo
      api_key: os.environ/OPENAI_API_KEY

  - model_name: o3-mini
    litellm_params:
      model: openai/o3-mini
      api_key: os.environ/OPENAI_API_KEY

  - model_name: gpt-5
    litellm_params:
      model: openai/gpt-5
      api_key: os.environ/OPENAI_API_KEY

  - model_name: gpt-5-mini
    litellm_params:
      model: openai/gpt-5-mini
      api_key: os.environ/OPENAI_API_KEY

  - model_name: gpt-5-nano
    litellm_params:
      model: openai/gpt-5-nano
      api_key: os.environ/OPENAI_API_KEY

  # Anthropic Models
  - model_name: claude-4-opus
    litellm_params:
      model: anthropic/claude-4-opus
      api_key: os.environ/ANTHROPIC_API_KEY # Set in environment variable

  - model_name: claude-4-sonnet
    litellm_params:
      model: anthropic/claude-4-sonnet
      api_key: os.environ/ANTHROPIC_API_KEY

  - model_name: claude-3.5-sonnet
    litellm_params:
      model: anthropic/claude-3-5-sonnet-20241022
      api_key: os.environ/ANTHROPIC_API_KEY

  - model_name: claude-3.5-haiku
    litellm_params:
      model: anthropic/claude-3-5-haiku-20241022
      api_key: os.environ/ANTHROPIC_API_KEY

  # Groq Models
  - model_name: gemma2-9b-it
    litellm_params:
      model: groq/gemma2-9b-it
      api_key: os.environ/GROQ_API_KEY

  - model_name: llama-3.1-8b-instant
    litellm_params:
      model: groq/llama-3.1-8b-instant
      api_key: os.environ/GROQ_API_KEY

  - model_name: llama-3.3-70b-versatile
    litellm_params:
      model: groq/llama-3.3-70b-versatile
      api_key: os.environ/GROQ_API_KEY

  - model_name: llama-guard-4-12b
    litellm_params:
      model: groq/meta-llama/llama-guard-4-12b
      api_key: os.environ/GROQ_API_KEY

  - model_name: whisper-large-v3
    litellm_params:
      model: groq/whisper-large-v3
      api_key: os.environ/GROQ_API_KEY

  - model_name: whisper-large-v3-turbo
    litellm_params:
      model: groq/whisper-large-v3-turbo
      api_key: os.environ/GROQ_API_KEY

  - model_name: gpt-oss-120b
    litellm_params:
      model: groq/openai/gpt-oss-120b
      api_key: os.environ/GROQ_API_KEY

  - model_name: gpt-oss-20b
    litellm_params:
      model: groq/openai/gpt-oss-20b
      api_key: os.environ/GROQ_API_KEY

  # DeepSeek Models
  - model_name: deepseek-chat
    litellm_params:
      model: deepseek/deepseek-chat
      api_key: os.environ/DEEPSEEK_API_KEY
      api_base: https://api.deepseek.com/v1

  - model_name: deepseek-reasoner
    litellm_params:
      model: deepseek/deepseek-reasoner
      api_key: os.environ/DEEPSEEK_API_KEY
      api_base: https://api.deepseek.com/v1

  # Gemini Models
  - model_name: gemini-2.5-pro
    litellm_params:
      model: gemini/gemini-2.5-pro
      api_key: os.environ/GEMINI_API_KEY

  - model_name: gemini-2.5-flash
    litellm_params:
      model: gemini/gemini-2.5-flash
      api_key: os.environ/GEMINI_API_KEY

  - model_name: gemini-2.5-flash-lite
    litellm_params:
      model: gemini/gemini-2.5-flash-lite
      api_key: os.environ/GEMINI_API_KEY

  # Perplexity Models
  - model_name: sonar-deep-research
    litellm_params:
      model: perplexity/sonar-deep-research
      api_key: os.environ/PERPLEXITYAI_API_KEY

  - model_name: sonar-reasoning-pro
    litellm_params:
      model: perplexity/sonar-reasoning-pro
      api_key: os.environ/PERPLEXITYAI_API_KEY

  - model_name: sonar-reasoning
    litellm_params:
      model: perplexity/sonar-reasoning
      api_key: os.environ/PERPLEXITYAI_API_KEY

  - model_name: sonar-pro
    litellm_params:
      model: perplexity/sonar-pro
      api_key: os.environ/PERPLEXITYAI_API_KEY

  - model_name: sonar
    litellm_params:
      model: perplexity/sonar
      api_key: os.environ/PERPLEXITYAI_API_KEY

  # xAI Models
  - model_name: grok-4-0709
    litellm_params:
      model: xai/grok-4-0709
      api_key: os.environ/XAI_API_KEY

  - model_name: grok-3
    litellm_params:
      model: xai/grok-3
      api_key: os.environ/XAI_API_KEY

  - model_name: grok-3-mini
    litellm_params:
      model: xai/grok-3-mini
      api_key: os.environ/XAI_API_KEY

  # Example: Azure OpenAI
  # - model_name: azure-gpt-4
  #   litellm_params:
  #     model: azure/gpt-4
  #     api_base: https://your-resource.openai.azure.com/
  #     api_key: ${AZURE_API_KEY}
  #     api_version: "2024-02-15-preview"

  # Example: Local Models (Ollama)
  # - model_name: llama2
  #   litellm_params:
  #     model: ollama/llama2
  #     api_base: http://localhost:11434

# General Settings
litellm_settings:
  drop_params: true
  max_tokens: 4096
  request_timeout: 600
  telemetry: false
  # success_callback: []  # Removed Langfuse callback



# Router Settings (Optional)
router_settings:
  routing_strategy: "simple-shuffle" # Options: simple-shuffle, least-busy, usage-based-routing
  # model_group_alias: {"gpt-4": ["gpt-4", "gpt-4-turbo"]}  # Group models together

# Database Configuration (Optional - for persistent key management)
database_type: "postgres"
database_args:
  host: "postgres"
  port: 5432
  user: "postgres"
  password: os.environ/POSTGRES_PASSWORD
  database: "litellm"
# File Upload Settings
files_settings:
  - custom_llm_provider: openai
    api_key: os.environ/OPENAI_API_KEY
  
  - custom_llm_provider: gemini
    api_key: os.environ/GEMINI_API_KEY
  
  - custom_llm_provider: anthropic
    api_key: os.environ/ANTHROPIC_API_KEY
  
  - custom_llm_provider: perplexity
    api_key: os.environ/PERPLEXITYAI_API_KEY
  
  - custom_llm_provider: xai
    api_key: os.environ/XAI_API_KEY

# Caching (Optional)
# cache:
#   type: "redis"
#   host: "redis"
#   port: 6379
#   ttl: 3600  # 1 hour

# Rate Limiting (Optional)
# rate_limit:
#   - model: "gpt-4"
#     max_calls: 100
#     time_window: 3600  # 1 hour
#   - model: "claude-3-opus"
#     max_calls: 50
#     time_window: 3600

# Budget/Cost Tracking (Optional)
# budget_limits:
#   - user: "default"
#     max_budget: 100  # $100
#     duration: "monthly"
